# site settings
title: Home
subtitle: 
email: mairead.heiger@virginia.edu
description: <a href="https://cosmicai.org/">CosmicAI</a> and <a href="https://astronomy.as.virginia.edu/galaxy-evolution-and-cosmology-initiative-geco">GECO</a> fellow at the University of Virginia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heigerm.github.io" # the base hostname & protocol for your site
author:
street_address: null
city: 
state: 
zip_code: 
country: 
phone: null

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/heigerm
  Orcid: https://orcid.org/0000-0002-2446-8332
  Google-Scholar: https://scholar.google.com/citations?hl=en&user=Frb1V4oAAAAJ 
  Instagram: 
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- elements.md
- landing.md
- all_posts.md
